### ISSUE TITLE
network population report: update legend to right side display, add layer tooltip functionality

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#47]
The network population overview report has the legend on the bottom, please switch to right side display.

/#/network/population

Please include legend interactivity for focusing on an individual series as implemented on the data density report.

Please add layer tooltip to show the value for each series as suggested here:

![image](https://user-images.githubusercontent.com/6586384/142448092-58e9f63d-43f6-46f2-9b3b-9baf394ee1eb.png)

and mentioned in #39

**Comment by Mikhail-iontsev** [comment]
There are currently limitations to the tooltip functionality. It seems it's not yet possible to show multiple tooltips at the same time using the standart tooltip config. There's a way though to show required data for each data point picked automatically on mouseover event: via the text mark. The problem is that if the data points are close enough the text marks would create an unreadable mess (please see the screenshot below)
![image](https://user-images.githubusercontent.com/92372420/143615626-54cfd699-143a-400f-bbb5-6f71701863d5.png)


One way to solve this is to use the standard tooltip, but show it only when the user moves the pointer over a data point. That way user experience would stay consistent regardless of the legend state (focus on a particular data series).

**Comment by fdefalco** [comment]
What about this example where they show a tooltip with multiple series? 

https://vega.github.io/vega-lite/examples/interactive_multi_line_pivot_tooltip.html

**Comment by Mikhail-iontsev** [comment]
The tooltip can display values of only one data point at a time.

The example above uses different fields of an object to display the tooltip. There's basically only one data point for each value on the X axis. What we have is a collection of objects each representing a data point which means we may have several different data points at the same X position (if >1 data sources).

In our case this approach would show the data point with the highest value on the Y axis.

**Comment by fdefalco** [comment]
With the limitations of the tooltips, I think I would prefer if we had multiple charts arranged vertically, or perhaps with the step height as is done on measurement units.  Do you want to propose a solution or would you like me to take this?

**Comment by Mikhail-iontsev** [comment]
Do i understand correctly that you suggest a faceted view, each of the graphs representing a data source?
![image](https://user-images.githubusercontent.com/92372420/145113392-a0b943db-291d-4032-a0a6-09697ffcd25f.png)
