### ISSUE TITLE
Create new Data Source Overview Report

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#98]
Create a new data source overview report, make this the default view for the data source report category, replacing the data quality history report.

In the report we will include:

- top level metrics:
  - number of releases
  - average days between releases
  - vuetify sparkline for number of people
  - vuetify sparkline for number of issues
 - main table below
   - table with release date, number of people and number data quality issues.  number of people and data quality issues should respectively link to the person report or data quality report for that release.

**Comment by Mikhail-iontsev** [comment]
Wouldn't it be better to use Vega lite instead of the Vuetify sparkline component? Vega lite would add a level of interactivity (such as a tooltip) that is yet impossible with the sparkline. Moreover, since the project already makes extensive use of Vega lite it seems reasonable to continue doing so.

**Comment by fdefalco** [comment]
That seems fine to me.
